packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@fontsource-variable/tasa-orbiter": ^5.2.2
  "@playwright/test": ^1.58.2
  "@types/node": ^24
  jose: ^6.2.2
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
