name: Build Desktop

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-desktop.yml
    permissions:
      contents: read
